services:
  - type: web
    name: amr-predictor
    env: python
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app --workers 1 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
